/*  js/engines/core-engines.js  -- The 6 primary generative engines
 *  Loaded via <script> tag AFTER engine-params.js.
 *  Uses window globals: ctx, gp, pcol, rng, rr, ri, fbm, h2r, lerp, setI, setPr, seed
 */

function flowfield(W,H,p){const np=gp('fp'),lf=gp('fl'),sc=gp('fs'),sp=gp('fv'),lw=gp('fw'),al=gp('fa')/100,cu=gp('fc'),ns=ri(0,99999);ctx.fillStyle=p.bg;ctx.fillRect(0,0,W,H);for(let i=0;i<np;i++){let x=rng()*W,y=rng()*H;ctx.strokeStyle=pcol(p,rng(),al);ctx.lineWidth=lw;ctx.beginPath();ctx.moveTo(x,y);for(let j=0;j<lf;j++){const nx=x/W*sc,ny=y/H*sc,n=fbm(nx,ny,ns),n2=fbm(nx+100,ny+100,ns+50);const a=n*Math.PI*4+cu*(n2-.5)*Math.PI*2;x+=Math.cos(a)*sp;y+=Math.sin(a)*sp;if(x<0||x>W||y<0||y>H)break;ctx.lineTo(x,y);}ctx.stroke();}setI(`${np} particles \u00d7 ${lf} steps`);}

function attractor(W,H,p){const it=gp('ai'),ps=gp('ap'),al=gp('aa')/100,ty=gp('at');ctx.fillStyle=p.bg;ctx.fillRect(0,0,W,H);let a,b,c,d,ok=false;for(let t=0;t<30&&!ok;t++){a=rr(-2.5,2.5);b=rr(-2.5,2.5);c=rr(-2.5,2.5);d=rr(-2.5,2.5);let x=.1,y=.1,sp=0;for(let i=0;i<2000;i++){const[nx,ny]=asc(ty,x,y,a,b,c,d);if(!isFinite(nx))break;x=nx;y=ny;if(i>100)sp=Math.max(sp,Math.abs(x),Math.abs(y));}if(sp>.4&&sp<80)ok=true;}let x=.1,y=.1,x0=1e9,x1=-1e9,y0=1e9,y1=-1e9;for(let i=0;i<6000;i++){const[nx,ny]=asc(ty,x,y,a,b,c,d);if(!isFinite(nx)){x=.1;y=.1;continue;}x=nx;y=ny;if(i>100){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}}const pd=28,rx=x1-x0||1,ry=y1-y0||1;x=.1;y=.1;for(let i=0;i<it;i++){const[nx,ny]=asc(ty,x,y,a,b,c,d);if(!isFinite(nx)){x=.1;y=.1;continue;}x=nx;y=ny;if(i<200)continue;ctx.fillStyle=pcol(p,i/it,al);ctx.fillRect(pd+(x-x0)/rx*(W-2*pd)-ps/2,pd+(y-y0)/ry*(H-2*pd)-ps/2,ps,ps);}setI(`${ty}, ${(it/1000)|0}k iterations`);}

const asc=(ty,x,y,a,b,c,d)=>{if(ty==='clifford')return[Math.sin(a*y)+c*Math.cos(a*x),Math.sin(b*x)+d*Math.cos(b*y)];if(ty==='dejong')return[Math.sin(a*y)-Math.cos(b*x),Math.sin(c*x)-Math.cos(d*y)];return[Math.sin(x*y/b)*y+Math.cos(a*x-y),x+Math.sin(y)/b];};

function subdivision(W,H,p){const dp=gp('dd'),ra=gp('dr'),ga=gp('dg'),cu=gp('dc'),st=gp('ds');ctx.fillStyle=p.bg;ctx.fillRect(0,0,W,H);const L=[];const sp=(x,y,w,h,d,hz)=>{if(!d||w<10||h<10){L.push({x,y,w,h});return;}const r=Math.max(.1,Math.min(.9,ra+(rng()-.5)*.3));if(rng()<.07){L.push({x,y,w,h});return;}const g=ga/2;if(hz){sp(x,y,w,h*r-g,d-1,!hz);sp(x,y+h*r+g,w,h*(1-r)-g,d-1,!hz);}else{sp(x,y,w*r-g,h,d-1,!hz);sp(x+w*r+g,y,w*(1-r)-g,h,d-1,!hz);}};sp(ga,ga,W-2*ga,H-2*ga,dp,rng()>.5);L.forEach((r,i)=>{const t=i/L.length,cr=Math.min(cu,r.w/2,r.h/2),dF=st==='fill'||(st==='mixed'&&rng()<.7),dS=st==='outline'||(st==='mixed'&&!dF);const dr=()=>{ctx.beginPath();if(cr>0){ctx.moveTo(r.x+cr,r.y);ctx.arcTo(r.x+r.w,r.y,r.x+r.w,r.y+r.h,cr);ctx.arcTo(r.x+r.w,r.y+r.h,r.x,r.y+r.h,cr);ctx.arcTo(r.x,r.y+r.h,r.x,r.y,cr);ctx.arcTo(r.x,r.y,r.x+r.w,r.y,cr);ctx.closePath();}else ctx.rect(r.x,r.y,r.w,r.h);};if(dF){ctx.fillStyle=pcol(p,t,1);dr();ctx.fill();}if(dS){ctx.strokeStyle=pcol(p,1-t,.6);ctx.lineWidth=1;dr();ctx.stroke();}});setI(`${L.length} regions, depth ${dp}, ${st}`);}

function interference(W,H,p){const n=gp('wn'),fr=gp('wf'),re=gp('wr'),mo=gp('wm');const src=Array.from({length:n},()=>({x:rr(.05,.95)*W,y:rr(.05,.95)*H,f:fr*rr(.4,1.6),ph:rng()*Math.PI*2,am:rr(.6,1)}));for(let py=0;py<H;py+=re){for(let px=0;px<W;px+=re){let s=0;src.forEach(q=>{const dx=px-q.x,dy=py-q.y;s+=Math.sin(Math.sqrt(dx*dx+dy*dy)/Math.max(W,H)*q.f*Math.PI*2-q.ph)*q.am;});s/=n;let t=mo==='sin'?(s+1)/2:mo==='abs'?Math.abs(s):mo==='tanh'?Math.tanh(s*2.5)*.5+.5:((((s+1)/2*255|0)^(Math.abs(s)*128|0)))/255;ctx.fillStyle=pcol(p,Math.max(0,Math.min(1,t)),1);ctx.fillRect(px,py,re,re);}if(py%50===0)setPr(py/H*100);}setI(`${n} sources, freq=${fr}, ${mo}`);}

function growth(W,H,p){const iN=gp('gn'),st=gp('gs'),rd=gp('gr'),id=gp('gi'),lw=gp('gw'),MX=600;ctx.fillStyle=p.bg;ctx.fillRect(0,0,W,H);let N=[];const cx=W*rr(.3,.7),cy=H*rr(.3,.7),r=Math.min(W,H)*rr(.1,.2);for(let i=0;i<iN;i++){const a=(i/iN)*Math.PI*2;N.push({x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r});}for(let s=0;s<st;s++){const n=N.length;N=N.map((q,i)=>{const pv=N[(i-1+n)%n],nt=N[(i+1)%n];let fx=(pv.x+nt.x)/2-q.x,fy=(pv.y+nt.y)/2-q.y;fx*=.4;fy*=.4;const str=Math.max(1,n/70|0);for(let k=0;k<n;k+=str){if(Math.abs(k-i)<3)continue;const dx=q.x-N[k].x,dy=q.y-N[k].y,d=Math.sqrt(dx*dx+dy*dy);if(d<rd&&d>0){const f=(rd-d)/rd*.55;fx+=dx/d*f;fy+=dy/d*f;}}if(q.x<20)fx+=.5;if(q.x>W-20)fx-=.5;if(q.y<20)fy+=.5;if(q.y>H-20)fy-=.5;return{x:q.x+fx,y:q.y+fy};});if(N.length<MX){const ins=[];N.forEach((q,i)=>{ins.push(q);const nt=N[(i+1)%N.length],dx=nt.x-q.x,dy=nt.y-q.y;if(Math.sqrt(dx*dx+dy*dy)>id)ins.push({x:(q.x+nt.x)/2+rr(-.2,.2),y:(q.y+nt.y)/2+rr(-.2,.2)});});N=ins;}if(s%12===0||s===st-1){ctx.strokeStyle=pcol(p,s/st,.4);ctx.lineWidth=lw*.4;ctx.beginPath();N.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();ctx.stroke();setPr(s/st*100);}}ctx.strokeStyle=pcol(p,1,.95);ctx.lineWidth=lw;ctx.beginPath();N.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();ctx.stroke();setI(`${N.length} nodes, ${st} steps`);}

function lissajous(W,H,p){const ro=gp('lr'),co=gp('lc'),tu=gp('lt'),lw=gp('lw'),al=gp('la')/100;ctx.fillStyle=p.bg;ctx.fillRect(0,0,W,H);const px=W*.05,py=H*.05,cw=(W-2*px)/co,ch=(H-2*py)/ro;const rf=Array.from({length:ro},(_,i)=>i+1+ri(0,2)),cf=Array.from({length:co},(_,i)=>i+1+ri(0,2));const ph=Array.from({length:ro},()=>Array.from({length:co},()=>rng()*Math.PI*2));for(let r=0;r<ro;r++)for(let c=0;c<co;c++){const cx=px+(c+.5)*cw,cy=py+(r+.5)*ch;ctx.strokeStyle=pcol(p,(r*co+c)/(ro*co),al);ctx.lineWidth=lw;ctx.beginPath();for(let i=0;i<=tu;i++){const t=i/tu*Math.PI*2;ctx[i?'lineTo':'moveTo'](cx+Math.sin(cf[c]*t+ph[r][c])*cw*.44,cy+Math.sin(rf[r]*t)*ch*.44);}ctx.stroke();}setI(`${ro}\u00d7${co} grid, ${tu} turns`);}

/* ── Expose on window ── */
window.flowfield=flowfield;
window.attractor=attractor;
window.asc=asc;
window.subdivision=subdivision;
window.interference=interference;
window.growth=growth;
window.lissajous=lissajous;
